In [2]:
## quickstart for beginners
import tensorflow as tf

In [6]:
## load and prepare the MNIST dataset and convert data type.
mnist = tf.keras.datasets.mnist   
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
## Build Sequential model: choose an optimizer and loss function for train.
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
## vector of logits or log-odds scores
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.22503556,  0.09626429,  0.6413267 ,  0.01157345,  0.45167017,
         0.48606908, -0.37829056, -0.11780791,  0.19931266,  0.17389107]],
      dtype=float32)

In [9]:
## softmax : converts these logits to probabilitires
tf.nn.softmax(predictions).numpy()

array([[0.0665883 , 0.09181988, 0.15836322, 0.08436376, 0.1310049 ,
        0.13558973, 0.05712683, 0.07412528, 0.10178647, 0.09923151]],
      dtype=float32)

In [10]:
## sparse : loss takes a vector of logits and true index and returs a scalar loss.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
## this loss is equal to the negative log probability
loss_fn(y_train[:1], predictions).numpy()

1.9981215

In [12]:
## model build with this loss function
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
## model parameteres to minimize the loss
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2954 - accuracy: 0.9135
Epoch 2/5
1875/1875 [==============================] - 2s 980us/step - loss: 0.1432 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 2s 952us/step - loss: 0.1099 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 2s 956us/step - loss: 0.0896 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 2s 990us/step - loss: 0.0766 - accuracy: 0.9768


In [14]:
## checks model performance with validation set or train set
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0848 - accuracy: 0.9749


[0.08479765057563782, 0.9749000072479248]

In [15]:
## model to return a probability (trained model, softmax)
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.27609564e-06, 6.07865147e-10, 2.19617263e-07, 1.16947442e-04,
        1.24376958e-11, 6.88083617e-07, 1.88162697e-11, 9.99863982e-01,
        1.07174472e-07, 1.47971605e-05],
       [2.40768736e-06, 3.20592044e-05, 9.99925613e-01, 7.82485495e-06,
        2.47443498e-14, 2.10127450e-06, 4.15042950e-06, 4.73078868e-12,
        2.57887859e-05, 1.26322970e-14],
       [5.84885015e-07, 9.98729527e-01, 2.31761980e-04, 7.85879183e-06,
        6.92180720e-06, 1.02366384e-05, 6.38855272e-05, 8.21204565e-04,
        1.27753694e-04, 6.31504165e-08],
       [9.99994397e-01, 6.18083145e-12, 1.48999902e-07, 2.45170515e-08,
        8.47267234e-09, 2.87154580e-06, 1.60890443e-06, 2.56689219e-07,
        4.48000463e-08, 7.89373189e-07],
       [1.81312180e-06, 5.75406300e-09, 1.82273686e-06, 1.15925353e-07,
        9.97225285e-01, 3.17036870e-06, 3.72868817e-06, 6.19714265e-04,
        2.69529028e-06, 2.14161514e-03]], dtype=float32)>